export interface NaturalTerms {
  singular: string
  plural: string
  article: string
  feminin: boolean
  synonyms: string[]
  intentVerbs: string[]
  qualifiers: string[]
  commonQueries: string[]
}

export const SHARED_VERBS = ['find', 'hire', 'consult', 'contact', 'compare']

export const NATURAL_TERMS: Record<string, NaturalTerms> = {
  'personal-injury': {
    singular: 'personal injury lawyer',
    plural: 'personal injury lawyers',
    article: 'a personal injury lawyer',
    feminin: false,
    synonyms: ['personal injury attorney', 'accident lawyer', 'injury attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'top-rated', 'experienced', 'affordable'],
    commonQueries: ['personal injury lawyer near me', 'how much does a personal injury lawyer cost'],
  },
  'car-accidents': {
    singular: 'car accident lawyer',
    plural: 'car accident lawyers',
    article: 'a car accident lawyer',
    feminin: false,
    synonyms: ['auto accident attorney', 'car crash lawyer', 'vehicle accident attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'top-rated', 'experienced', 'affordable', 'free consultation'],
    commonQueries: ['car accident lawyer near me', 'do I need a lawyer after a car accident'],
  },
  'truck-accidents': {
    singular: 'truck accident lawyer',
    plural: 'truck accident lawyers',
    article: 'a truck accident lawyer',
    feminin: false,
    synonyms: ['trucking accident attorney', '18-wheeler accident lawyer', 'semi-truck crash attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['truck accident lawyer near me', 'how much is a truck accident settlement'],
  },
  'motorcycle-accidents': {
    singular: 'motorcycle accident lawyer',
    plural: 'motorcycle accident lawyers',
    article: 'a motorcycle accident lawyer',
    feminin: false,
    synonyms: ['motorcycle crash attorney', 'bike accident lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['motorcycle accident lawyer near me', 'motorcycle accident settlement amounts'],
  },
  'slip-and-fall': {
    singular: 'slip and fall lawyer',
    plural: 'slip and fall lawyers',
    article: 'a slip and fall lawyer',
    feminin: false,
    synonyms: ['premises liability attorney', 'trip and fall lawyer', 'slip and fall accident attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['slip and fall lawyer near me', 'how much is a slip and fall case worth'],
  },
  'medical-malpractice': {
    singular: 'medical malpractice lawyer',
    plural: 'medical malpractice lawyers',
    article: 'a medical malpractice lawyer',
    feminin: false,
    synonyms: ['medical negligence attorney', 'med mal lawyer', 'healthcare malpractice attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'top-rated', 'experienced', 'board-certified'],
    commonQueries: ['medical malpractice lawyer near me', 'how to sue a doctor for malpractice'],
  },
  'wrongful-death': {
    singular: 'wrongful death lawyer',
    plural: 'wrongful death lawyers',
    article: 'a wrongful death lawyer',
    feminin: false,
    synonyms: ['wrongful death attorney', 'fatal accident lawyer', 'death claim attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'compassionate', 'top-rated'],
    commonQueries: ['wrongful death lawyer near me', 'how much is a wrongful death lawsuit worth'],
  },
  'product-liability': {
    singular: 'product liability lawyer',
    plural: 'product liability lawyers',
    article: 'a product liability lawyer',
    feminin: false,
    synonyms: ['defective product attorney', 'product injury lawyer', 'product recall attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['product liability lawyer near me', 'how to sue a company for a defective product'],
  },
  'workers-compensation': {
    singular: 'workers compensation lawyer',
    plural: 'workers compensation lawyers',
    article: 'a workers compensation lawyer',
    feminin: false,
    synonyms: ['workers comp attorney', 'work injury lawyer', 'on-the-job injury attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable', 'free consultation'],
    commonQueries: ['workers comp lawyer near me', 'do I need a lawyer for workers compensation'],
  },
  'nursing-home-abuse': {
    singular: 'nursing home abuse lawyer',
    plural: 'nursing home abuse lawyers',
    article: 'a nursing home abuse lawyer',
    feminin: false,
    synonyms: ['elder abuse attorney', 'nursing home neglect lawyer', 'care facility abuse attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'compassionate'],
    commonQueries: ['nursing home abuse lawyer near me', 'signs of nursing home abuse'],
  },
  'criminal-defense': {
    singular: 'criminal defense lawyer',
    plural: 'criminal defense lawyers',
    article: 'a criminal defense lawyer',
    feminin: false,
    synonyms: ['criminal defense attorney', 'criminal lawyer', 'defense attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'top-rated', 'aggressive', 'experienced', 'affordable'],
    commonQueries: ['criminal defense lawyer near me', 'how much does a criminal lawyer cost'],
  },
  'dui-dwi': {
    singular: 'DUI lawyer',
    plural: 'DUI lawyers',
    article: 'a DUI lawyer',
    feminin: false,
    synonyms: ['DWI attorney', 'drunk driving lawyer', 'DUI defense attorney', 'impaired driving lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'affordable', 'experienced', 'top-rated'],
    commonQueries: ['DUI lawyer near me', 'how much does a DUI lawyer cost', 'do I need a lawyer for a DUI'],
  },
  'drug-crimes': {
    singular: 'drug crime lawyer',
    plural: 'drug crime lawyers',
    article: 'a drug crime lawyer',
    feminin: false,
    synonyms: ['drug offense attorney', 'narcotics defense lawyer', 'drug possession attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'aggressive'],
    commonQueries: ['drug crime lawyer near me', 'drug possession penalties'],
  },
  'white-collar-crime': {
    singular: 'white collar crime lawyer',
    plural: 'white collar crime lawyers',
    article: 'a white collar crime lawyer',
    feminin: false,
    synonyms: ['white collar criminal attorney', 'fraud defense lawyer', 'embezzlement attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['white collar crime lawyer near me', 'federal fraud defense attorney'],
  },
  'federal-crimes': {
    singular: 'federal crime lawyer',
    plural: 'federal crime lawyers',
    article: 'a federal crime lawyer',
    feminin: false,
    synonyms: ['federal criminal defense attorney', 'federal defense lawyer', 'federal court attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['federal crime lawyer near me', 'difference between state and federal charges'],
  },
  'juvenile-crimes': {
    singular: 'juvenile crime lawyer',
    plural: 'juvenile crime lawyers',
    article: 'a juvenile crime lawyer',
    feminin: false,
    synonyms: ['juvenile defense attorney', 'minor crime lawyer', 'youth criminal attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'compassionate'],
    commonQueries: ['juvenile crime lawyer near me', 'what happens when a minor is charged with a crime'],
  },
  'sex-crimes': {
    singular: 'sex crime lawyer',
    plural: 'sex crime lawyers',
    article: 'a sex crime lawyer',
    feminin: false,
    synonyms: ['sex offense attorney', 'sexual assault defense lawyer', 'sex crime defense attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'discreet', 'aggressive'],
    commonQueries: ['sex crime lawyer near me', 'sex offender registration defense'],
  },
  'theft-robbery': {
    singular: 'theft lawyer',
    plural: 'theft lawyers',
    article: 'a theft lawyer',
    feminin: false,
    synonyms: ['robbery attorney', 'shoplifting lawyer', 'burglary defense attorney', 'larceny lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['theft lawyer near me', 'penalties for robbery'],
  },
  'violent-crimes': {
    singular: 'violent crime lawyer',
    plural: 'violent crime lawyers',
    article: 'a violent crime lawyer',
    feminin: false,
    synonyms: ['assault defense attorney', 'violent offense lawyer', 'aggravated assault attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'aggressive', 'top-rated'],
    commonQueries: ['violent crime lawyer near me', 'assault and battery defense'],
  },
  'traffic-violations': {
    singular: 'traffic violation lawyer',
    plural: 'traffic violation lawyers',
    article: 'a traffic violation lawyer',
    feminin: false,
    synonyms: ['traffic ticket attorney', 'speeding ticket lawyer', 'moving violation attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'affordable', 'experienced'],
    commonQueries: ['traffic violation lawyer near me', 'should I fight a traffic ticket'],
  },
  'divorce': {
    singular: 'divorce lawyer',
    plural: 'divorce lawyers',
    article: 'a divorce lawyer',
    feminin: false,
    synonyms: ['divorce attorney', 'family law attorney', 'dissolution lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'affordable', 'experienced', 'top-rated', 'female', 'male'],
    commonQueries: ['divorce lawyer near me', 'how much does a divorce lawyer cost', 'do I need a divorce lawyer'],
  },
  'child-custody': {
    singular: 'child custody lawyer',
    plural: 'child custody lawyers',
    article: 'a child custody lawyer',
    feminin: false,
    synonyms: ['custody attorney', 'child custody attorney', 'parental rights lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable', 'aggressive'],
    commonQueries: ['child custody lawyer near me', 'how to get full custody of a child'],
  },
  'child-support': {
    singular: 'child support lawyer',
    plural: 'child support lawyers',
    article: 'a child support lawyer',
    feminin: false,
    synonyms: ['child support attorney', 'child maintenance lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'affordable', 'experienced'],
    commonQueries: ['child support lawyer near me', 'how is child support calculated'],
  },
  'adoption': {
    singular: 'adoption lawyer',
    plural: 'adoption lawyers',
    article: 'an adoption lawyer',
    feminin: false,
    synonyms: ['adoption attorney', 'child adoption lawyer', 'adoption agency attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'compassionate'],
    commonQueries: ['adoption lawyer near me', 'how much does adoption cost'],
  },
  'alimony-spousal-support': {
    singular: 'alimony lawyer',
    plural: 'alimony lawyers',
    article: 'an alimony lawyer',
    feminin: false,
    synonyms: ['spousal support attorney', 'alimony attorney', 'maintenance lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['alimony lawyer near me', 'how is alimony calculated'],
  },
  'domestic-violence': {
    singular: 'domestic violence lawyer',
    plural: 'domestic violence lawyers',
    article: 'a domestic violence lawyer',
    feminin: false,
    synonyms: ['domestic abuse attorney', 'restraining order lawyer', 'protective order attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'compassionate', 'free consultation'],
    commonQueries: ['domestic violence lawyer near me', 'how to get a restraining order'],
  },
  'prenuptial-agreements': {
    singular: 'prenuptial agreement lawyer',
    plural: 'prenuptial agreement lawyers',
    article: 'a prenuptial agreement lawyer',
    feminin: false,
    synonyms: ['prenup attorney', 'premarital agreement lawyer', 'prenuptial lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['prenup lawyer near me', 'how much does a prenup cost'],
  },
  'paternity': {
    singular: 'paternity lawyer',
    plural: 'paternity lawyers',
    article: 'a paternity lawyer',
    feminin: false,
    synonyms: ['paternity attorney', 'paternity test lawyer', 'father rights attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['paternity lawyer near me', 'how to establish paternity'],
  },
  'business-law': {
    singular: 'business lawyer',
    plural: 'business lawyers',
    article: 'a business lawyer',
    feminin: false,
    synonyms: ['business attorney', 'commercial lawyer', 'corporate counsel'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated', 'affordable'],
    commonQueries: ['business lawyer near me', 'do I need a lawyer to start a business'],
  },
  'corporate-law': {
    singular: 'corporate lawyer',
    plural: 'corporate lawyers',
    article: 'a corporate lawyer',
    feminin: false,
    synonyms: ['corporate attorney', 'corporation lawyer', 'business formation attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['corporate lawyer near me', 'corporate lawyer vs business lawyer'],
  },
  'mergers-acquisitions': {
    singular: 'mergers and acquisitions lawyer',
    plural: 'mergers and acquisitions lawyers',
    article: 'a mergers and acquisitions lawyer',
    feminin: false,
    synonyms: ['M&A attorney', 'merger lawyer', 'acquisition attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['M&A lawyer near me', 'mergers and acquisitions process'],
  },
  'contract-law': {
    singular: 'contract lawyer',
    plural: 'contract lawyers',
    article: 'a contract lawyer',
    feminin: false,
    synonyms: ['contract attorney', 'contract review lawyer', 'contract dispute attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['contract lawyer near me', 'how much does a contract lawyer cost'],
  },
  'business-litigation': {
    singular: 'business litigation lawyer',
    plural: 'business litigation lawyers',
    article: 'a business litigation lawyer',
    feminin: false,
    synonyms: ['commercial litigation attorney', 'business dispute lawyer', 'civil litigation attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'aggressive', 'top-rated'],
    commonQueries: ['business litigation lawyer near me', 'how to sue a business'],
  },
  'intellectual-property': {
    singular: 'intellectual property lawyer',
    plural: 'intellectual property lawyers',
    article: 'an intellectual property lawyer',
    feminin: false,
    synonyms: ['IP attorney', 'intellectual property attorney', 'IP lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['IP lawyer near me', 'how to protect intellectual property'],
  },
  'trademark': {
    singular: 'trademark lawyer',
    plural: 'trademark lawyers',
    article: 'a trademark lawyer',
    feminin: false,
    synonyms: ['trademark attorney', 'trademark registration lawyer', 'brand protection attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['trademark lawyer near me', 'how much does it cost to trademark a name'],
  },
  'patent': {
    singular: 'patent lawyer',
    plural: 'patent lawyers',
    article: 'a patent lawyer',
    feminin: false,
    synonyms: ['patent attorney', 'patent agent', 'patent prosecution lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'registered'],
    commonQueries: ['patent lawyer near me', 'how much does a patent cost'],
  },
  'copyright': {
    singular: 'copyright lawyer',
    plural: 'copyright lawyers',
    article: 'a copyright lawyer',
    feminin: false,
    synonyms: ['copyright attorney', 'copyright infringement lawyer', 'DMCA attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['copyright lawyer near me', 'how to copyright something'],
  },
  'real-estate-law': {
    singular: 'real estate lawyer',
    plural: 'real estate lawyers',
    article: 'a real estate lawyer',
    feminin: false,
    synonyms: ['real estate attorney', 'property lawyer', 'real estate closing attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable', 'top-rated'],
    commonQueries: ['real estate lawyer near me', 'do I need a lawyer to buy a house'],
  },
  'landlord-tenant': {
    singular: 'landlord tenant lawyer',
    plural: 'landlord tenant lawyers',
    article: 'a landlord tenant lawyer',
    feminin: false,
    synonyms: ['tenant rights attorney', 'landlord attorney', 'eviction lawyer', 'rental dispute attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'affordable', 'experienced'],
    commonQueries: ['landlord tenant lawyer near me', 'can a landlord evict me without notice'],
  },
  'foreclosure': {
    singular: 'foreclosure lawyer',
    plural: 'foreclosure lawyers',
    article: 'a foreclosure lawyer',
    feminin: false,
    synonyms: ['foreclosure defense attorney', 'mortgage default lawyer', 'foreclosure prevention attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['foreclosure lawyer near me', 'how to stop foreclosure'],
  },
  'zoning-land-use': {
    singular: 'zoning lawyer',
    plural: 'zoning lawyers',
    article: 'a zoning lawyer',
    feminin: false,
    synonyms: ['land use attorney', 'zoning and land use lawyer', 'planning attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'local'],
    commonQueries: ['zoning lawyer near me', 'how to get a zoning variance'],
  },
  'construction-law': {
    singular: 'construction lawyer',
    plural: 'construction lawyers',
    article: 'a construction lawyer',
    feminin: false,
    synonyms: ['construction attorney', 'construction defect lawyer', 'building dispute attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['construction lawyer near me', 'construction defect lawsuit'],
  },
  'immigration-law': {
    singular: 'immigration lawyer',
    plural: 'immigration lawyers',
    article: 'an immigration lawyer',
    feminin: false,
    synonyms: ['immigration attorney', 'immigration counsel', 'visa lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable', 'Spanish-speaking', 'top-rated'],
    commonQueries: ['immigration lawyer near me', 'how much does an immigration lawyer cost'],
  },
  'green-cards': {
    singular: 'green card lawyer',
    plural: 'green card lawyers',
    article: 'a green card lawyer',
    feminin: false,
    synonyms: ['green card attorney', 'permanent residency lawyer', 'green card application attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['green card lawyer near me', 'how long does it take to get a green card'],
  },
  'visa-applications': {
    singular: 'visa lawyer',
    plural: 'visa lawyers',
    article: 'a visa lawyer',
    feminin: false,
    synonyms: ['visa attorney', 'visa application lawyer', 'work visa attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['visa lawyer near me', 'how to apply for a work visa'],
  },
  'deportation-defense': {
    singular: 'deportation defense lawyer',
    plural: 'deportation defense lawyers',
    article: 'a deportation defense lawyer',
    feminin: false,
    synonyms: ['deportation attorney', 'removal defense lawyer', 'immigration defense attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'aggressive', 'urgent'],
    commonQueries: ['deportation defense lawyer near me', 'how to fight deportation'],
  },
  'asylum': {
    singular: 'asylum lawyer',
    plural: 'asylum lawyers',
    article: 'an asylum lawyer',
    feminin: false,
    synonyms: ['asylum attorney', 'political asylum lawyer', 'refugee attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'pro bono'],
    commonQueries: ['asylum lawyer near me', 'how to apply for asylum in the US'],
  },
  'citizenship-naturalization': {
    singular: 'citizenship lawyer',
    plural: 'citizenship lawyers',
    article: 'a citizenship lawyer',
    feminin: false,
    synonyms: ['naturalization attorney', 'US citizenship lawyer', 'citizenship application attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['citizenship lawyer near me', 'how to become a US citizen'],
  },
  'estate-planning': {
    singular: 'estate planning lawyer',
    plural: 'estate planning lawyers',
    article: 'an estate planning lawyer',
    feminin: false,
    synonyms: ['estate planning attorney', 'estate lawyer', 'trust attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable', 'top-rated'],
    commonQueries: ['estate planning lawyer near me', 'how much does estate planning cost'],
  },
  'wills-trusts': {
    singular: 'wills and trusts lawyer',
    plural: 'wills and trusts lawyers',
    article: 'a wills and trusts lawyer',
    feminin: false,
    synonyms: ['will attorney', 'trust lawyer', 'estate attorney', 'living trust attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['wills and trusts lawyer near me', 'how much does a will cost'],
  },
  'probate': {
    singular: 'probate lawyer',
    plural: 'probate lawyers',
    article: 'a probate lawyer',
    feminin: false,
    synonyms: ['probate attorney', 'estate administration lawyer', 'probate court attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['probate lawyer near me', 'how long does probate take'],
  },
  'elder-law': {
    singular: 'elder law lawyer',
    plural: 'elder law lawyers',
    article: 'an elder law lawyer',
    feminin: false,
    synonyms: ['elder law attorney', 'senior citizen lawyer', 'aging law attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'compassionate'],
    commonQueries: ['elder law lawyer near me', 'elder law attorney for Medicaid planning'],
  },
  'guardianship': {
    singular: 'guardianship lawyer',
    plural: 'guardianship lawyers',
    article: 'a guardianship lawyer',
    feminin: false,
    synonyms: ['guardianship attorney', 'conservatorship lawyer', 'legal guardian attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['guardianship lawyer near me', 'how to get guardianship of a parent'],
  },
  'employment-law': {
    singular: 'employment lawyer',
    plural: 'employment lawyers',
    article: 'an employment lawyer',
    feminin: false,
    synonyms: ['employment attorney', 'labor lawyer', 'workplace attorney', 'employee rights lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated', 'affordable'],
    commonQueries: ['employment lawyer near me', 'when should I hire an employment lawyer'],
  },
  'wrongful-termination': {
    singular: 'wrongful termination lawyer',
    plural: 'wrongful termination lawyers',
    article: 'a wrongful termination lawyer',
    feminin: false,
    synonyms: ['wrongful firing attorney', 'unlawful termination lawyer', 'wrongful dismissal attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'aggressive'],
    commonQueries: ['wrongful termination lawyer near me', 'was I wrongfully terminated'],
  },
  'workplace-discrimination': {
    singular: 'workplace discrimination lawyer',
    plural: 'workplace discrimination lawyers',
    article: 'a workplace discrimination lawyer',
    feminin: false,
    synonyms: ['employment discrimination attorney', 'workplace discrimination attorney', 'EEOC lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'aggressive'],
    commonQueries: ['workplace discrimination lawyer near me', 'how to file an EEOC complaint'],
  },
  'sexual-harassment': {
    singular: 'sexual harassment lawyer',
    plural: 'sexual harassment lawyers',
    article: 'a sexual harassment lawyer',
    feminin: false,
    synonyms: ['sexual harassment attorney', 'workplace harassment lawyer', 'Title VII attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'confidential', 'compassionate'],
    commonQueries: ['sexual harassment lawyer near me', 'how to report sexual harassment at work'],
  },
  'wage-hour-claims': {
    singular: 'wage and hour lawyer',
    plural: 'wage and hour lawyers',
    article: 'a wage and hour lawyer',
    feminin: false,
    synonyms: ['unpaid wages attorney', 'overtime lawyer', 'FLSA attorney', 'wage theft lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable'],
    commonQueries: ['wage and hour lawyer near me', 'how to recover unpaid wages'],
  },
  'bankruptcy': {
    singular: 'bankruptcy lawyer',
    plural: 'bankruptcy lawyers',
    article: 'a bankruptcy lawyer',
    feminin: false,
    synonyms: ['bankruptcy attorney', 'debt lawyer', 'insolvency attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'affordable', 'experienced', 'top-rated', 'free consultation'],
    commonQueries: ['bankruptcy lawyer near me', 'how much does it cost to file bankruptcy'],
  },
  'chapter-7-bankruptcy': {
    singular: 'Chapter 7 bankruptcy lawyer',
    plural: 'Chapter 7 bankruptcy lawyers',
    article: 'a Chapter 7 bankruptcy lawyer',
    feminin: false,
    synonyms: ['Chapter 7 attorney', 'liquidation bankruptcy lawyer', 'Chapter 7 filing attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'affordable', 'experienced'],
    commonQueries: ['Chapter 7 lawyer near me', 'do I qualify for Chapter 7'],
  },
  'chapter-13-bankruptcy': {
    singular: 'Chapter 13 bankruptcy lawyer',
    plural: 'Chapter 13 bankruptcy lawyers',
    article: 'a Chapter 13 bankruptcy lawyer',
    feminin: false,
    synonyms: ['Chapter 13 attorney', 'reorganization bankruptcy lawyer', 'Chapter 13 repayment attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'affordable', 'experienced'],
    commonQueries: ['Chapter 13 lawyer near me', 'Chapter 7 vs Chapter 13'],
  },
  'debt-relief': {
    singular: 'debt relief lawyer',
    plural: 'debt relief lawyers',
    article: 'a debt relief lawyer',
    feminin: false,
    synonyms: ['debt settlement attorney', 'debt negotiation lawyer', 'debt consolidation attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'affordable', 'experienced'],
    commonQueries: ['debt relief lawyer near me', 'how to get out of debt'],
  },
  'tax-law': {
    singular: 'tax lawyer',
    plural: 'tax lawyers',
    article: 'a tax lawyer',
    feminin: false,
    synonyms: ['tax attorney', 'tax law attorney', 'IRS tax lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated', 'affordable'],
    commonQueries: ['tax lawyer near me', 'do I need a tax lawyer'],
  },
  'irs-disputes': {
    singular: 'IRS dispute lawyer',
    plural: 'IRS dispute lawyers',
    article: 'an IRS dispute lawyer',
    feminin: false,
    synonyms: ['IRS attorney', 'tax controversy lawyer', 'IRS audit attorney', 'tax resolution lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'aggressive'],
    commonQueries: ['IRS dispute lawyer near me', 'how to deal with IRS problems'],
  },
  'tax-planning': {
    singular: 'tax planning lawyer',
    plural: 'tax planning lawyers',
    article: 'a tax planning lawyer',
    feminin: false,
    synonyms: ['tax planning attorney', 'tax advisor lawyer', 'tax strategy attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['tax planning lawyer near me', 'how to reduce taxes legally'],
  },
  'entertainment-law': {
    singular: 'entertainment lawyer',
    plural: 'entertainment lawyers',
    article: 'an entertainment lawyer',
    feminin: false,
    synonyms: ['entertainment attorney', 'music lawyer', 'media attorney', 'film lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['entertainment lawyer near me', 'do I need an entertainment lawyer'],
  },
  'environmental-law': {
    singular: 'environmental lawyer',
    plural: 'environmental lawyers',
    article: 'an environmental lawyer',
    feminin: false,
    synonyms: ['environmental attorney', 'environmental compliance lawyer', 'EPA attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['environmental lawyer near me', 'environmental law firms'],
  },
  'health-care-law': {
    singular: 'health care lawyer',
    plural: 'health care lawyers',
    article: 'a health care lawyer',
    feminin: false,
    synonyms: ['healthcare attorney', 'health law lawyer', 'medical regulation attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['health care lawyer near me', 'healthcare compliance attorney'],
  },
  'insurance-law': {
    singular: 'insurance lawyer',
    plural: 'insurance lawyers',
    article: 'an insurance lawyer',
    feminin: false,
    synonyms: ['insurance attorney', 'insurance claim lawyer', 'bad faith insurance attorney', 'insurance dispute lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'aggressive'],
    commonQueries: ['insurance lawyer near me', 'insurance company denied my claim'],
  },
  'civil-rights': {
    singular: 'civil rights lawyer',
    plural: 'civil rights lawyers',
    article: 'a civil rights lawyer',
    feminin: false,
    synonyms: ['civil rights attorney', 'constitutional lawyer', 'Section 1983 attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['civil rights lawyer near me', 'how to file a civil rights lawsuit'],
  },
  'consumer-protection': {
    singular: 'consumer protection lawyer',
    plural: 'consumer protection lawyers',
    article: 'a consumer protection lawyer',
    feminin: false,
    synonyms: ['consumer rights attorney', 'consumer fraud lawyer', 'UDAP attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'aggressive'],
    commonQueries: ['consumer protection lawyer near me', 'how to sue a company for fraud'],
  },
  'social-security-disability': {
    singular: 'Social Security disability lawyer',
    plural: 'Social Security disability lawyers',
    article: 'a Social Security disability lawyer',
    feminin: false,
    synonyms: ['SSDI attorney', 'disability lawyer', 'Social Security attorney', 'SSI lawyer'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'free consultation', 'no upfront fee'],
    commonQueries: ['disability lawyer near me', 'how to apply for Social Security disability'],
  },
  'veterans-benefits': {
    singular: 'veterans benefits lawyer',
    plural: 'veterans benefits lawyers',
    article: 'a veterans benefits lawyer',
    feminin: false,
    synonyms: ['VA benefits attorney', 'veterans disability lawyer', 'VA claims attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'free consultation'],
    commonQueries: ['veterans benefits lawyer near me', 'how to appeal a VA disability decision'],
  },
  'class-action': {
    singular: 'class action lawyer',
    plural: 'class action lawyers',
    article: 'a class action lawyer',
    feminin: false,
    synonyms: ['class action attorney', 'mass tort lawyer', 'class action litigation attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['class action lawyer near me', 'how to join a class action lawsuit'],
  },
  'appeals': {
    singular: 'appeals lawyer',
    plural: 'appeals lawyers',
    article: 'an appeals lawyer',
    feminin: false,
    synonyms: ['appellate attorney', 'appellate lawyer', 'appeals court attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'top-rated'],
    commonQueries: ['appeals lawyer near me', 'how to appeal a court decision'],
  },
  'mediation-arbitration': {
    singular: 'mediation lawyer',
    plural: 'mediation lawyers',
    article: 'a mediation lawyer',
    feminin: false,
    synonyms: ['arbitration attorney', 'mediator', 'dispute resolution lawyer', 'ADR attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'certified'],
    commonQueries: ['mediation lawyer near me', 'mediation vs arbitration'],
  },
  'family-law': {
    singular: 'family lawyer',
    plural: 'family lawyers',
    article: 'a family lawyer',
    feminin: false,
    synonyms: ['family law attorney', 'family court lawyer', 'domestic relations attorney'],
    intentVerbs: ['find', 'hire', 'consult'],
    qualifiers: ['best', 'experienced', 'affordable', 'compassionate'],
    commonQueries: ['family lawyer near me', 'how much does a family lawyer cost'],
  },
}

/** Get natural terms for a service slug, with safe fallback */
export function getNaturalTerm(specialtySlug: string): NaturalTerms {
  return NATURAL_TERMS[specialtySlug] ?? {
    singular: specialtySlug.replace(/-/g, ' '),
    plural: specialtySlug.replace(/-/g, ' ') + 's',
    article: `a ${specialtySlug.replace(/-/g, ' ')}`,
    feminin: false,
    synonyms: [],
    intentVerbs: SHARED_VERBS,
    qualifiers: [],
    commonQueries: [],
  }
}
