// Navigation data - shared between server and client components

export const popularServices = [
  { name: 'Plombier', slug: 'plombier', icon: 'Wrench' },
  { name: 'Électricien', slug: 'electricien', icon: 'Zap' },
  { name: 'Serrurier', slug: 'serrurier', icon: 'Key' },
  { name: 'Chauffagiste', slug: 'chauffagiste', icon: 'Flame' },
  { name: 'Peintre', slug: 'peintre-en-batiment', icon: 'PaintBucket' },
  { name: 'Menuisier', slug: 'menuisier', icon: 'Hammer' },
  { name: 'Maçon', slug: 'macon', icon: 'HardHat' },
  { name: 'Jardinier', slug: 'jardinier', icon: 'TreeDeciduous' },
]

export const popularCities = [
  { name: 'Paris', slug: 'paris', department: '75' },
  { name: 'Lyon', slug: 'lyon', department: '69' },
  { name: 'Marseille', slug: 'marseille', department: '13' },
  { name: 'Toulouse', slug: 'toulouse', department: '31' },
  { name: 'Bordeaux', slug: 'bordeaux', department: '33' },
  { name: 'Lille', slug: 'lille', department: '59' },
  { name: 'Nantes', slug: 'nantes', department: '44' },
  { name: 'Nice', slug: 'nice', department: '06' },
  { name: 'Strasbourg', slug: 'strasbourg', department: '67' },
  { name: 'Montpellier', slug: 'montpellier', department: '34' },
]

export const relatedServices: Record<string, string[]> = {
  'plombier': ['chauffagiste', 'salle-de-bain', 'cuisiniste', 'climaticien', 'pompe-a-chaleur'],
  'electricien': ['domoticien', 'alarme-securite', 'borne-recharge', 'antenniste', 'panneaux-solaires'],
  'serrurier': ['alarme-securite', 'vitrier', 'metallier', 'ferronnier'],
  'chauffagiste': ['plombier', 'climaticien', 'pompe-a-chaleur', 'ramoneur', 'isolation-thermique'],
  'peintre-en-batiment': ['facadier', 'platrier', 'decorateur', 'carreleur', 'poseur-de-parquet'],
  'menuisier': ['charpentier', 'poseur-de-parquet', 'cuisiniste', 'storiste', 'ferronnier'],
  'macon': ['terrassier', 'charpentier', 'couvreur', 'facadier', 'etancheiste'],
  'jardinier': ['paysagiste', 'pisciniste', 'terrassier', 'cloturiste', 'nettoyage'],
  'carreleur': ['poseur-de-parquet', 'salle-de-bain', 'peintre-en-batiment', 'platrier', 'solier'],
  'couvreur': ['charpentier', 'zingueur', 'etancheiste', 'facadier', 'ramoneur'],
  'climaticien': ['chauffagiste', 'pompe-a-chaleur', 'plombier', 'isolation-thermique', 'electricien'],
  'vitrier': ['miroitier', 'menuisier', 'storiste', 'serrurier', 'alarme-securite'],
  'cuisiniste': ['plombier', 'electricien', 'salle-de-bain', 'carreleur', 'decorateur'],
  'solier': ['poseur-de-parquet', 'carreleur', 'peintre-en-batiment', 'decorateur'],
  'nettoyage': ['ramoneur', 'facadier', 'desinsectisation', 'deratisation', 'jardinier'],
  'terrassier': ['macon', 'paysagiste', 'pisciniste', 'geometre', 'charpentier'],
  'charpentier': ['couvreur', 'menuisier', 'macon', 'zingueur', 'terrassier'],
  'zingueur': ['couvreur', 'charpentier', 'etancheiste', 'facadier', 'plombier'],
  'etancheiste': ['couvreur', 'facadier', 'zingueur', 'macon', 'isolation-thermique'],
  'facadier': ['peintre-en-batiment', 'etancheiste', 'macon', 'isolation-thermique', 'nettoyage'],
  'platrier': ['peintre-en-batiment', 'carreleur', 'decorateur', 'poseur-de-parquet', 'isolation-thermique'],
  'metallier': ['ferronnier', 'serrurier', 'menuisier', 'alarme-securite', 'storiste'],
  'ferronnier': ['metallier', 'serrurier', 'menuisier', 'decorateur', 'macon'],
  'poseur-de-parquet': ['solier', 'carreleur', 'menuisier', 'peintre-en-batiment', 'decorateur'],
  'miroitier': ['vitrier', 'menuisier', 'storiste', 'decorateur', 'salle-de-bain'],
  'storiste': ['vitrier', 'miroitier', 'menuisier', 'alarme-securite', 'climaticien'],
  'salle-de-bain': ['plombier', 'carreleur', 'electricien', 'cuisiniste', 'decorateur'],
  'architecte-interieur': ['decorateur', 'cuisiniste', 'salle-de-bain', 'peintre-en-batiment', 'menuisier'],
  'decorateur': ['architecte-interieur', 'peintre-en-batiment', 'poseur-de-parquet', 'cuisiniste', 'storiste'],
  'domoticien': ['electricien', 'alarme-securite', 'borne-recharge', 'antenniste', 'climaticien'],
  'pompe-a-chaleur': ['chauffagiste', 'climaticien', 'plombier', 'isolation-thermique', 'panneaux-solaires'],
  'panneaux-solaires': ['electricien', 'pompe-a-chaleur', 'borne-recharge', 'couvreur', 'renovation-energetique'],
  'isolation-thermique': ['facadier', 'renovation-energetique', 'platrier', 'couvreur', 'climaticien'],
  'renovation-energetique': ['isolation-thermique', 'pompe-a-chaleur', 'panneaux-solaires', 'chauffagiste', 'diagnostiqueur'],
  'borne-recharge': ['electricien', 'domoticien', 'panneaux-solaires', 'alarme-securite'],
  'ramoneur': ['chauffagiste', 'couvreur', 'nettoyage', 'charpentier', 'diagnostiqueur'],
  'paysagiste': ['jardinier', 'pisciniste', 'terrassier', 'macon', 'decorateur'],
  'pisciniste': ['paysagiste', 'terrassier', 'macon', 'electricien', 'plombier'],
  'alarme-securite': ['serrurier', 'electricien', 'domoticien', 'antenniste', 'vitrier'],
  'antenniste': ['electricien', 'domoticien', 'alarme-securite', 'couvreur'],
  'ascensoriste': ['electricien', 'metallier', 'macon', 'diagnostiqueur'],
  'diagnostiqueur': ['renovation-energetique', 'electricien', 'ramoneur', 'geometre', 'isolation-thermique'],
  'geometre': ['terrassier', 'macon', 'diagnostiqueur', 'architecte-interieur', 'paysagiste'],
  'desinsectisation': ['deratisation', 'nettoyage', 'jardinier', 'diagnostiqueur'],
  'deratisation': ['desinsectisation', 'nettoyage', 'jardinier', 'diagnostiqueur'],
  'demenageur': ['nettoyage', 'peintre-en-batiment', 'electricien', 'plombier', 'serrurier'],
}

export const popularRegions = [
  { name: 'Île-de-France', slug: 'ile-de-france' },
  { name: 'Auvergne-Rhône-Alpes', slug: 'auvergne-rhone-alpes' },
  { name: 'Provence-Alpes-Côte d\'Azur', slug: 'provence-alpes-cote-d-azur' },
  { name: 'Occitanie', slug: 'occitanie' },
  { name: 'Nouvelle-Aquitaine', slug: 'nouvelle-aquitaine' },
  { name: 'Hauts-de-France', slug: 'hauts-de-france' },
]
