/**
 * Voice Lead Routing — US Attorneys
 *
 * Creates a lead (devis_request) from a qualified voice call,
 * dispatches it to a matching attorney, and notifies via SMS.
 *
 * Server-side only — uses createAdminClient() (service_role, bypasses RLS).
 */

import type { SupabaseClient } from '@supabase/supabase-js'
import { createAdminClient } from '@/lib/supabase/admin'
import { sendSMS } from '@/lib/notifications/sms'
import { logLeadEvent } from '@/lib/dashboard/events'
import { logger } from '@/lib/logger'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface VoiceCallWithQualification {
  id: string
  contact_id: string | null
  conversation_id: string | null
  qualification_score: string | null
  qualification_data: Record<string, unknown> | null
  caller_phone: string
}

// ---------------------------------------------------------------------------
// Vertical → service name mapping
// ---------------------------------------------------------------------------

const VERTICAL_SERVICE_MAP: Record<string, string> = {
  pac: 'Heat Pump Installation',
  toiture: 'Roofing Work',
  isolation: 'Thermal Insulation',
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/**
 * Create a devis_request from a qualified voice call, find a matching attorney,
 * assign the lead, and notify the attorney via SMS.
 */
export async function createVoiceLead(
  _supabase: SupabaseClient,
  voiceCall: VoiceCallWithQualification
): Promise<void> {
  const log = logger.child({ action: 'voice_lead_routing', voiceCallId: voiceCall.id })
  const admin = createAdminClient()

  const qualData = voiceCall.qualification_data ?? {}
  const projectType = (qualData.project_type as string) ?? null
  const postalCode = (qualData.postal_code as string) ?? null
  const callerName = (qualData.caller_name as string) ?? 'Voice prospect'
  const budgetRange = (qualData.budget_range as string) ?? null
  const urgency = (qualData.urgency as string) ?? 'normal'

  // Map vertical to service name
  const specialtyName = projectType ? VERTICAL_SERVICE_MAP[projectType] ?? projectType : 'Energy Renovation'

  // ------------------------------------------------------------------
  // 1. Create the devis_request (lead)
  // ------------------------------------------------------------------
  log.info('Creating devis_request from voice call', { projectType, postalCode })

  const validUrgency = ['normal', 'urgent', 'very_urgent'].includes(urgency) ? urgency : 'normal'

  const { data: lead, error: leadError } = await admin
    .from('devis_requests')
    .insert({
      service_name: specialtyName,
      postal_code: postalCode || '00000',
      city: (qualData.city as string) ?? null,
      description: `Lead generated by voice qualification (score ${voiceCall.qualification_score ?? 'N/A'}). Project: ${specialtyName}.`,
      budget: budgetRange,
      urgency: validUrgency,
      status: 'pending',
      client_name: callerName,
      client_email: (qualData.email as string) ?? `voice+${voiceCall.id.slice(0, 8)}@us-attorneys.com`,
      client_phone: voiceCall.caller_phone,
    })
    .select('id')
    .single()

  if (leadError || !lead) {
    log.error('Failed to create devis_request', leadError)
    return
  }

  log.info('Devis request created', { leadId: lead.id })

  // ------------------------------------------------------------------
  // 2. Link voice_call → lead
  // ------------------------------------------------------------------
  const { error: linkError } = await admin
    .from('voice_calls')
    .update({ lead_id: lead.id })
    .eq('id', voiceCall.id)

  if (linkError) {
    log.warn('Failed to link voice_call to lead', { error: linkError.message })
  }

  // ------------------------------------------------------------------
  // 3. Log the lead creation event
  // ------------------------------------------------------------------
  await logLeadEvent(lead.id, 'created', {
    metadata: {
      source: 'voice',
      voice_call_id: voiceCall.id,
      qualification_score: voiceCall.qualification_score,
      project_type: projectType,
    },
  })

  // ------------------------------------------------------------------
  // 4. Find matching attorney (specialty + location from postal code)
  // ------------------------------------------------------------------
  const department = postalCode ? postalCode.slice(0, 2) : null

  let matchQuery = admin
    .from('attorneys')
    .select('id, name, phone, email, user_id')
    .eq('is_active', true)

  if (specialtyName) {
    matchQuery = matchQuery.ilike('specialty', `%${specialtyName}%`)
  }

  if (department) {
    // Match providers whose address_postal_code starts with the same department
    matchQuery = matchQuery.ilike('address_postal_code', `${department}%`)
  }

  // Round-robin: prefer providers who haven't received a lead recently
  matchQuery = matchQuery
    .order('last_lead_assigned_at', { ascending: true, nullsFirst: true })
    .limit(1)

  const { data: providers, error: attorneyError } = await matchQuery

  if (attorneyError) {
    log.error('Failed to query matching providers', attorneyError)
    return
  }

  if (!providers || providers.length === 0) {
    log.warn('No matching attorney found', { specialtyName, department })
    return
  }

  const artisan = providers[0]
  log.info('Matched attorney', { attorneyId: artisan.id, attorneyName: artisan.name })

  // ------------------------------------------------------------------
  // 5. Create lead_assignment
  // ------------------------------------------------------------------
  const { error: assignError } = await admin
    .from('lead_assignments')
    .insert({
      lead_id: lead.id,
      attorney_id: artisan.id,
      status: 'pending',
      source_table: 'devis_requests',
    })

  if (assignError) {
    log.error('Failed to create lead_assignment', assignError)
    return
  }

  // Update round-robin counter
  await admin
    .from('attorneys')
    .update({ last_lead_assigned_at: new Date().toISOString() })
    .eq('id', artisan.id)

  // Log the dispatch event
  await logLeadEvent(lead.id, 'dispatched', {
    attorneyId: artisan.id,
    metadata: {
      source: 'voice',
      voice_call_id: voiceCall.id,
    },
  })

  log.info('Lead assigned to attorney', { leadId: lead.id, attorneyId: artisan.id })

  // ------------------------------------------------------------------
  // 6. Notify attorney via SMS
  // ------------------------------------------------------------------
  if (artisan.phone) {
    const location = postalCode ? ` (${postalCode})` : ''
    const smsMessage =
      `New lead on US Attorneys!\n` +
      `${specialtyName}${location}\n` +
      `Client: ${callerName}\n` +
      `Log in to respond: us-attorneys.com/attorney-dashboard/leads`

    const smsResult = await sendSMS(artisan.phone, smsMessage)

    if (smsResult.success) {
      log.info('Attorney notified via SMS', { attorneyId: artisan.id, messageId: smsResult.messageId })
    } else {
      log.warn('SMS notification failed', { attorneyId: artisan.id, error: smsResult.error })
    }
  } else {
    log.warn('Attorney has no phone number, SMS skipped', { attorneyId: artisan.id })
  }
}
